first_name = input("name")
last_name = input("last name? ")
age = input("How old are you? ")
phone_number = input("Your phone number? ")
print(f"Your first name, last name: {first_name} {last_name}")
print(f"Your age: {age}")
print(f"Your phone number: {phone_number}")